### ISSUE TITLE
Fetch restaurants from Yelp api. 

### ISSUE THREAD

**Issue by wbissac723** [wbissac723/meal-vote#2]
<img width="1191" alt="screen shot 2019-02-16 at 7 40 29 am" src="https://user-images.githubusercontent.com/23244582/52900673-2bce5300-31be-11e9-8ecb-d3a03eea90ec.png">
Not able to fetch data from Yelp api.  Works in Postman, but not in app. I created an HttpInterceptor to append the api key "token", but functionality is not working.

<img width="1085" alt="screen shot 2019-02-16 at 7 37 55 am" src="https://user-images.githubusercontent.com/23244582/52900635-d5611480-31bd-11e9-914c-a7cbcde4bf49.png">

**Comment by chauhansaurabh2** [comment]
Did a pull request for this error.
 But the yelp api seems to have not allowed CORS header , hence the OPTIONS call is failing and giving 403 error. Some links below to discuss this , we may need to hack 
https://github.com/tonybadguy/yelp-fusion/issues/8 
https://github.com/Yelp/yelp-fusion/issues/21
https://github.com/Yelp/yelp-api/issues/99
https://stackoverflow.com/questions/52397770/angular-6-yelp-fusion-api-get-request
![image](https://user-images.githubusercontent.com/34607427/52905171-fcd6d200-31fb-11e9-84d7-ed40e971e315.png)

**Comment by wbissac723** [comment]
Resolved issue with the creation of proxy. Configuration is found in proxy.config.json.  Created Express app to handle http requests.
